---
- name : setup Hello docker Environment
  hosts: localhost
  become: true
  vars:
    deploy_env : "{{ deploy_env  | default('production') }}"

  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker compose is installed
      apt:
        name: docker-compose
        state: present

    - name: Build the hello-react Docker image
      community.docker.docker_image_build:
        name: hello-react
        path: "{{ playbook_dir }}/../hello-react"
        dockerfile: Dockerfile
        args:
          REACT_ENV_FILE: "env.{{ deploy_env }}"
        rebuild: "{{ 'always' if force_rebuild | default(false) else 'never' }}"
        tag: latest

    - name: pull necessary Docker images
      community.docker.docker_image:
        name: "{{item }}"
        source: pull
      loop:
        - grafana/loki:latest
        - grafana/promtail:latest
        - grafana/grafana:latest

    - name: start Docker compose
      community.docker.docker_compose:
        project_src: "{{ playbook_dir }}/.."
        build: yes
        recreate: always
        remove_orphans: yes

